# Generated by Django 4.1.3 on 2022-11-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exemplo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='comida_favorita',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cor_favorita',
        ),
    ]
